- name: Insall prerequisite
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

- name: add the GPG key for the official Docker repository to your system
  raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Adding repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install docker
  apt:
    name: "{{ item }}"
  with_items:
  - docker-ce
  - docker-compose  

- name: Bootstrap a host without python2 installed
  raw: pip install docker-py

